export const KWS = ["CALCULATE","CALCULATEX","FILTER","ALL","ALLEXCEPT","ALLSELECTED","VALUES",
  "DISTINCT","RELATED","RELATEDTABLE","SUMMARIZE","ADDCOLUMNS","SELECTCOLUMNS","TOPN",
  "VAR","RETURN","IF","SWITCH","TRUE","FALSE","BLANK","IFERROR","ISBLANK","NOT","AND","OR",
  "DATESINPERIOD","DATESBETWEEN","DATESMTD","DATESQTD","DATESYTD","SAMEPERIODLASTYEAR",
  "PREVIOUSMONTH","PREVIOUSQUARTER","PREVIOUSYEAR","PARALLELPERIOD",
  "TOTALYTD","TOTALMTD","TOTALQTD","FIRSTDATE","LASTDATE","STARTOFMONTH","ENDOFMONTH",
  "LASTNONBLANK","FIRSTNONBLANK","KEEPFILTERS","INTERSECT","EXCEPT","UNION","DATEADD",
  "CALCULATETABLE","CONTAINS","IN","GENERATE"];
export const FNS = ["SUM","SUMX","AVERAGE","AVERAGEX","COUNT","COUNTA","COUNTROWS","COUNTBLANK",
  "DISTINCTCOUNT","MAX","MAXX","MIN","MINX","DIVIDE","RANKX","DATEDIFF","TODAY","NOW",
  "YEAR","MONTH","DAY","DATE","EOMONTH","WEEKDAY","FORMAT","INT","ABS","ROUND","MEDIANX",
  "TEXT","VALUE","LEFT","RIGHT","MID","LEN","TRIM","CONCATENATE","CONCATENATEX",
  "SELECTEDVALUE","HASONEFILTER","TOPN","IFERROR","ISBLANK","ABS"];
