import type { Formula } from "./types";

export function buildScript(tbl: string, selected: Formula[]): string {
  const ts = new Date().toLocaleString("en-GB", {
    dateStyle: "medium",
    timeStyle: "short",
  });
  const lines: string[] = [
    "-- ==============================================================",
    "--  DAX Measures Script",
    "--  Generated by DAX Formula Library",
    "--  Date  : " + ts,
    "--  Target: '" + tbl + "' table",
    "--  Count : " + selected.length + " measure" + (selected.length !== 1 ? "s" : ""),
    "--  Note  : For [KPI] time measures, Find & Replace [KPI]",
    "--          with Revenue, Cost, Headcount, Units, etc.",
    "-- ==============================================================",
    "",
    "DEFINE",
  ];
  selected.forEach((f) => {
    const eqIdx = f.dax.indexOf("=");
    const expr = eqIdx >= 0 ? f.dax.slice(eqIdx + 1).trim() : f.dax.trim();
    const indented = expr
      .split("\n")
      .map((l) => "        " + l)
      .join("\n");
    lines.push("    -- " + f.q);
    lines.push("    MEASURE '" + tbl + "'[" + f.title + "] =");
    lines.push(indented);
    lines.push("");
  });
  lines.push("EVALUATE");
  lines.push("    ROW(");
  lines.push(
    '        "Status", "✅ ' +
      selected.length +
      " measure" +
      (selected.length !== 1 ? "s" : "") +
      " created in '" +
      tbl +
      "'\",",
  );
  lines.push(
    '        "Tip", "For [KPI] measures: Find & Replace [KPI] with your measure base name"',
  );
  lines.push("    )");
  return lines.join("\n");
}
